# Generated by Django 3.0.8 on 2020-08-04 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("cosmos", "0001_init_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeListPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cosmos_cms_committeelistpluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("committees", models.ManyToManyField(to="cosmos.Committee")),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="BoardListPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cosmos_cms_boardlistpluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("boards", models.ManyToManyField(to="cosmos.Board")),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        ),
    ]
