# Generated by Django 3.0.8 on 2020-08-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("cosmos_cms", "0002_text_image_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cosmos_cms_contactpluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Optional. Title of the widget.", max_length=64, verbose_name="title"
                    ),
                ),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        ),
    ]
