# Generated by Django 3.0.8 on 2020-09-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0003_profile_terms_newsletter_fields"),
        ("cms", "0022_auto_20180620_1551"),
        ("cosmos_cms", "0003_contactpluginmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardSubpageTitlePluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cosmos_cms_boardsubpagetitlepluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("board", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cosmos.Board")),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="CommitteeSubpageTitlePluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cosmos_cms_committeesubpagetitlepluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("committee", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="cosmos.Committee")),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        ),
    ]
