# Generated by Django 3.0.8 on 2020-08-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0003_profile_terms_newsletter_fields"),
        ("cms", "0022_auto_20180620_1551"),
        ("cosmos_cms", "0004_committee_subpage_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardSubpageTitlePluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cosmos_cms_boardsubpagetitlepluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("subtitle", models.CharField(default="", max_length=100)),
                ("description", models.CharField(default="", max_length=400)),
                ("board", models.OneToOneField(on_delete=models.deletion.CASCADE, to="cosmos.Board")),
            ],
            options={"abstract": False},
            bases=("cms.cmsplugin",),
        ),
    ]
