# Generated by Django 3.0.8 on 2020-09-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos_cms", "0004_subpage_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeelistpluginmodel",
            name="button",
            field=models.BooleanField(default=True, verbose_name="use button"),
        ),
    ]
