repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: ''
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-django
      - pep8-naming
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3.9