# Generated by Django 3.2.7 on 2021-10-13 17:05

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="GMM",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("date", models.DateField()),
                    ],
                    options={
                        "verbose_name": "GMM",
                        "verbose_name_plural": "GMMs",
                    },
                ),
                migrations.CreateModel(
                    name="Partner",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("name", models.TextField()),
                        ("image", models.ImageField(upload_to="partners")),
                        ("url", models.URLField(blank=True)),
                    ],
                ),
                migrations.CreateModel(
                    name="PhotoAlbum",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("date", models.DateField()),
                        ("album_cover", models.ImageField(upload_to="photos")),
                    ],
                ),
                migrations.CreateModel(
                    name="Testimonial",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("text", models.TextField()),
                        ("author", models.CharField(max_length=100)),
                    ],
                ),
                migrations.CreateModel(
                    name="PhotoObject",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("photo", models.ImageField(upload_to="photos")),
                        (
                            "album",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="has_photos",
                                to="core.photoalbum",
                            ),
                        ),
                    ],
                ),
                migrations.CreateModel(
                    name="News",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("title", models.CharField(max_length=255)),
                        ("image", models.ImageField(upload_to="news")),
                        ("content", ckeditor.fields.RichTextField()),
                        ("lead", models.TextField(blank=True)),
                        ("publish_date", models.DateField()),
                        ("member_only", models.BooleanField()),
                        (
                            "author",
                            models.ForeignKey(
                                blank=True,
                                default=None,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="author",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
                migrations.CreateModel(
                    name="FileObject",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("name", models.CharField(max_length=255)),
                        ("created", models.DateTimeField(auto_now_add=True)),
                        ("modified", models.DateTimeField(auto_now=True)),
                        ("file", models.FileField(upload_to="gmm/")),
                        (
                            "container",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, related_name="has_files", to="core.gmm"
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                default=None,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="gmm_created_by",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "modified_by",
                            models.ForeignKey(
                                blank=True,
                                default=None,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="gmm_modified_by",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
            ],
            # Tables already exist, migrated over from cosmos app
            database_operations=[],
        ),
    ]
