# Generated by Django 3.0.10 on 2020-10-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_slugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="status",
        ),
    ]
