# Generated by Django 3.0.10 on 2020-11-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_status"),
        ("users", "0004_profile_newsletter_recipient"),
    ]

    operations = []
