# Generated by Django 3.0.11 on 2021-03-23 07:25

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.users.migrations.0006_institutionfontys_institutiontue
def update_profile(apps, schema_editor):
    old_profile = apps.get_model("users", "profile")
    institution = apps.get_model("users", "InstitutionTue")

    for instance in old_profile.objects.all():
        institution.objects.create(
            profile=instance,
            department=instance.department,
            program=instance.program,
            tue_id=instance.tue_id,
            card_number=instance.card_number,
            key_access=instance.key_access,
        )


class Migration(migrations.Migration):
    replaces = [
        ("users", "0006_institutionfontys_institutiontue"),
        ("users", "0007_remove_old_fields"),
        ("users", "0008_refactor_institutions"),
    ]

    dependencies = [
        ("users", "0004_remove_profile_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionTue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Biomedical Engineering", "Biomedical Engineering"),
                            ("Built Environment", "Built Environment"),
                            ("Chemical Engineering", "Chemical Engineering"),
                            ("Electrical Engineering", "Electrical Engineering"),
                            ("Industrial Design", "Industrial Design"),
                            ("Industrial Engineering", "Industrial Engineering"),
                            ("Mathematics and Computer Science", "Mathematics and Computer Science"),
                            ("Mechanical Engineering", "Mechanical Engineering"),
                            ("Physics", "Physics"),
                            ("Psychology and Technology", "Psychology and Technology"),
                            ("Sustainable Innovation", "Sustainable Innovation"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("PDEng", "PDEng"),
                            ("PHD", "PHD"),
                            ("Exchange", "Exchange"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("tue_id", models.CharField(blank=True, max_length=25, verbose_name="TU/e Student Number")),
                ("card_number", models.CharField(blank=True, max_length=25)),
                ("key_access", models.BooleanField(default=False, max_length=3)),
                ("profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.Profile")),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionFontys",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("study", models.CharField(choices=[("test", "test")], max_length=100)),
                ("profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.Profile")),
            ],
        ),
        migrations.RunPython(
            code=update_profile,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="profile",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="key_access",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="program",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="tue_id",
        ),
        migrations.AlterModelOptions(
            name="institutionfontys",
            options={"verbose_name": "Member of Fontys", "verbose_name_plural": "Members of Fontys"},
        ),
        migrations.AlterModelOptions(
            name="institutiontue",
            options={"verbose_name": "Member of TU/e", "verbose_name_plural": "Members of TU/e"},
        ),
    ]
