# Generated by Django 3.0.11 on 2020-11-30 17:56

import django.db.models.deletion
from django.db import migrations, models


def update_profile(apps, schema_editor):
    old_profile = apps.get_model("users", "profile")
    institution = apps.get_model("users", "InstitutionTue")

    for instance in old_profile.objects.all():
        institution.objects.create(
            profile=instance,
            department=instance.department,
            program=instance.program,
            tue_id=instance.tue_id,
            card_number=instance.card_number,
            key_access=instance.key_access,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_profile_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionTue",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Biomedical Engineering", "Biomedical Engineering"),
                            ("Built Environment", "Built Environment"),
                            ("Chemical Engineering", "Chemical Engineering"),
                            ("Electrical Engineering", "Electrical Engineering"),
                            ("Industrial Design", "Industrial Design"),
                            ("Industrial Engineering", "Industrial Engineering"),
                            ("Mathematics and Computer Science", "Mathematics and Computer Science"),
                            ("Mechanical Engineering", "Mechanical Engineering"),
                            ("Physics", "Physics"),
                            ("Psychology and Technology", "Psychology and Technology"),
                            ("Sustainable Innovation", "Sustainable Innovation"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("PDEng", "PDEng"),
                            ("PHD", "PHD"),
                            ("Exchange", "Exchange"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("tue_id", models.CharField(blank=True, max_length=25, verbose_name="TU/e Student Number")),
                ("card_number", models.CharField(blank=True, max_length=25)),
                ("key_access", models.BooleanField(default=False, max_length=3)),
                ("profile", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.Profile")),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionFontys",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("study", models.CharField(choices=[("test", "test")], max_length=100)),
                (
                    "profile",
                    models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to="users.Profile"),
                ),
            ],
        ),
        migrations.RunPython(update_profile, reverse_code=migrations.RunPython.noop),
    ]
