# Generated by Django 3.0.11 on 2021-03-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_institutionfontys_institutiontue"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="newsletter_recipient",
            field=models.CharField(
                choices=[("TUE", "TU/e email"), ("ALT", "Personal email")],
                default="TUE",
                max_length=3,
                verbose_name="Newsletter subscription email",
            ),
        ),
    ]
