# Generated by Django 3.0.11 on 2021-03-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_old_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutionfontys",
            name="profile",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="users.Profile"),
        ),
        migrations.AlterModelOptions(
            name="institutionfontys",
            options={"verbose_name": "Member of Fontys", "verbose_name_plural": "Members of Fontys"},
        ),
        migrations.AlterModelOptions(
            name="institutiontue",
            options={"verbose_name": "Member of TU/e", "verbose_name_plural": "Members of TU/e"},
        ),
    ]
