# Generated by Django 3.0.11 on 2021-03-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_refactor_institutions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="committee",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
