# Generated by Django 3.1.12 on 2021-06-14 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_change_to_bigautofield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committee",
            name="board",
        ),
        migrations.DeleteModel(
            name="GroupMember",
        ),
    ]
