# Generated by Django 3.2.4 on 2021-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_cleanup_group_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="slug",
            field=models.CharField(default="None", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="committee",
            name="slug",
            field=models.CharField(default="None", max_length=20, unique=True),
        ),
    ]
