# Generated by Django 3.2.4 on 2021-11-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_committee_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscribed_gmm_invite",
            field=models.BooleanField(default=False),
        ),
    ]
