# Generated by Django 3.2.9 on 2021-11-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_profile_subscribed_gmm_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="newsletter_recipient",
            field=models.CharField(
                choices=[("TUE", "TU/e email"), ("ALT", "Personal email")],
                default="TUE",
                max_length=3,
                verbose_name="Emails are sent to",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subscribed_gmm_invite",
            field=models.BooleanField(default=False, verbose_name="Subscribe to GMM invites"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subscribed_newsletter",
            field=models.BooleanField(default=False, verbose_name="Subscribe to the newsletter"),
        ),
    ]
