# Generated by Django 3.2.9 on 2021-12-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_profile_fields_verbose_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutiontue",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="institutiontue",
            name="key_access",
        ),
        migrations.RemoveField(
            model_name="institutiontue",
            name="tue_id",
        ),
    ]
