# Generated by Django 3.0.11 on 2021-03-01 17:31

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    replaces = [
        ("cms_plugins", "0001_initial"),
        ("cms_plugins", "0002_initial_fields"),
        ("cms_plugins", "0003_committeelist_button"),
        ("cms_plugins", "0004_delete_contactpluginmodel"),
        ("cms_plugins", "0005_text_to_htmlfield"),
        ("cms_plugins", "0006_foreign_key"),
    ]

    initial = True

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("users", "0001_initial"),
        ("users", "0002_text_to_htmlfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardListPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_plugins_boardlistpluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("boards", models.ManyToManyField(to="users.Board")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="CommitteeListPluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_plugins_committeelistpluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("committees", models.ManyToManyField(to="users.Committee")),
                ("button", models.BooleanField(default=True, verbose_name="use button")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="TextImagePluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_plugins_textimagepluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("text", djangocms_text_ckeditor.fields.HTMLField(blank=True)),
                ("Button", models.BooleanField(default=False, verbose_name="use button")),
                ("ButtonLink", models.URLField(blank=True)),
                ("ButtonText", models.CharField(blank=True, max_length=20)),
                ("image", models.ImageField(default="img/default.jpg", upload_to="cardImg")),
                ("orientation", models.BooleanField(default=False, verbose_name="image on the left")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="BoardSubpageTitlePluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_plugins_boardsubpagetitlepluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.Board")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="CommitteeSubpageTitlePluginModel",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="cms_plugins_committeesubpagetitlepluginmodel",
                        serialize=False,
                        to="cms.CMSPlugin",
                    ),
                ),
                ("committee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.Committee")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
