# Generated by Django 3.0.11 on 2021-03-01 17:32

from django.db import migrations


class Migration(migrations.Migration):
    """
    TODO Remove when migration has been run on live server
    """

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("cms_plugins", "0001_squashed_init_cms_plugins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardsubpagetitlepluginmodel",
            name="board",
        ),
        migrations.RemoveField(
            model_name="boardsubpagetitlepluginmodel",
            name="cmsplugin_ptr",
        ),
        migrations.RemoveField(
            model_name="committeelistpluginmodel",
            name="cmsplugin_ptr",
        ),
        migrations.RemoveField(
            model_name="committeelistpluginmodel",
            name="committees",
        ),
        migrations.RemoveField(
            model_name="committeesubpagetitlepluginmodel",
            name="cmsplugin_ptr",
        ),
        migrations.RemoveField(
            model_name="committeesubpagetitlepluginmodel",
            name="committee",
        ),
        migrations.RemoveField(
            model_name="textimagepluginmodel",
            name="cmsplugin_ptr",
        ),
        migrations.DeleteModel(
            name="BoardListPluginModel",
        ),
        migrations.DeleteModel(
            name="BoardSubpageTitlePluginModel",
        ),
        migrations.DeleteModel(
            name="CommitteeListPluginModel",
        ),
        migrations.DeleteModel(
            name="CommitteeSubpageTitlePluginModel",
        ),
        migrations.DeleteModel(
            name="TextImagePluginModel",
        ),
    ]
