# Generated by Django 3.0.8 on 2020-09-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("cms_plugins", "0003_committeelist_button"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactPluginModel",
        ),
    ]
