# Generated by Django 3.0.8 on 2020-10-01 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_text_to_htmlfield"),
        ("cms_plugins", "0005_text_to_htmlfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardsubpagetitlepluginmodel",
            name="board",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.Board"),
        ),
        migrations.AlterField(
            model_name="committeesubpagetitlepluginmodel",
            name="committee",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.Committee"),
        ),
    ]
