# Generated by Django 3.0.8 on 2020-07-23 07:55

from django.conf import settings
from django.db import migrations, models

from cosmos.models.group_member import ROLES
from cosmos.models.user.constants import DEPARTMENTS, NATIONALITIES, PROGRAMS, STATUSES


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0011_update_proxy_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("pretix_organizer_token", models.CharField(max_length=20)),
                ("group", models.OneToOneField(on_delete=models.deletion.CASCADE, to="auth.Group")),
            ],
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=list(enumerate(ROLES)), default="General Member", max_length=20)),
                ("group", models.OneToOneField(on_delete=models.deletion.CASCADE, to="auth.Group")),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),),
            ],
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(blank=True)),
                ("pretix_team_token", models.CharField(max_length=64)),
                ("board", models.ForeignKey(on_delete=models.deletion.CASCADE, to="cosmos.Board")),
                ("group", models.OneToOneField(on_delete=models.deletion.CASCADE, to="auth.Group")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("department", models.CharField(choices=list(zip(DEPARTMENTS, DEPARTMENTS)), max_length=100)),
                ("program", models.CharField(choices=list(zip(PROGRAMS, PROGRAMS)), max_length=100)),
                ("nationality", models.CharField(choices=list(zip(NATIONALITIES, NATIONALITIES)), max_length=100)),
                ("tue_id", models.CharField(blank=True, max_length=25, verbose_name="TU/e Number")),
                ("card_number", models.CharField(blank=True, max_length=25)),
                ("key_access", models.BooleanField(default=False, max_length=3)),
                ("status", models.CharField(choices=list(zip(STATUSES, STATUSES)), default="Pending", max_length=50)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),),
            ],
        ),
    ]
