# Generated by Django 3.0.8 on 2020-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0001_init_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="board", name="photo", field=models.ImageField(default="boards/default.jpg", upload_to="boards"),
        ),
    ]
