# Generated by Django 3.1.11 on 2021-05-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmm',
            name='minutes',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gmm',
            name='slides',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
