# Generated by Django 3.0.8 on 2020-07-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="gender",),
    ]
