# Generated by Django 3.0.8 on 2020-08-17 06:54

from django.db import migrations, models

import cosmos.models.board
import cosmos.models.committee


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0001_init_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="photo",
            field=models.ImageField(
                default="boards/default.jpg", upload_to="boards", validators=[cosmos.models.board.validate_aspect_ratio]
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="photo",
            field=models.ImageField(
                default="committees/default.png",
                upload_to="committees",
                validators=[cosmos.models.committee.validate_aspect_ratio],
            ),
        ),
    ]
