# Generated by Django 3.0.8 on 2020-08-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0002_board_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="photo",
            field=models.ImageField(default="boards/default.jpg", upload_to="committees"),
        ),
    ]
