# Generated by Django 3.0.8 on 2020-08-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0002_photo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="terms_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscribed_newsletter",
            field=models.BooleanField(default=False),
        ),
    ]
