# Generated by Django 3.2.4 on 2021-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0002_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="lead",
            field=models.TextField(blank=True),
        ),
    ]
