# Generated by Django 3.0.8 on 2020-08-28 18:20

import django.db.models.deletion
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0003_profile_terms_newsletter_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="members",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="board", name="pretix_organizer_token", field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="committee",
            name="board",
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to="cosmos.Board"),
        ),
    ]
