# Generated by Django 3.2.4 on 2021-09-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0004_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("image", models.ImageField(upload_to="partners")),
                ("url", models.URLField(blank=True)),
            ],
        ),
    ]
