# Generated by Django 3.2.4 on 2021-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cosmos", "0004_news_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="member_only",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
