name: Format

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - name: Run black
        uses: psf/black@stable
      - name: Set up pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install requirements
        run: pipenv install --deploy --dev
      - name: Run isort
        run: pipenv run isort **/*.py -c