name: Test

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 2020123
          POSTGRES_USER: github_actions
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5 --name postgres

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5 --name redis

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
          cache: 'pipenv'
      - name: Set up pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install requirements
        run: pipenv install --deploy --dev
      - name: Move secrets
        run: mv secrets.json.template tests/secrets.json
      - name: Run tests
        run: |
          npm install
          pipenv run ./manage.py collectstatic
          pipenv run ./manage.py test
